'use strict';
const $=s=>document.querySelector(s);let limit=6;
const mapping={q:'#query',audience:'#audience',stage:'#stage',type:'#format'};
function state(){return Object.fromEntries(Object.entries(mapping).map(([k,s])=>[k,$(s).value]));}
function filtered(){return LeadershipDiscovery.filter(CATALOG,state());}
function render(){const s=state(),rows=filtered();$('#result-count').textContent=`${rows.length} ${rows.length===1?'opportunity':'opportunities'} found${rows.length?' · Showing '+Math.min(limit,rows.length):''}`;$('#audience-help').textContent=audienceHelp(s.audience);$('#results').innerHTML=rows.slice(0,limit).map(r=>`<article class="opportunity" data-record="${escapeText(r.id)}"><div class="opportunity-top"><span class="audience-badge">${escapeText(r.audienceLabel)}</span><span class="learning-kind">${escapeText(r.type)}</span></div><p class="provider">${escapeText(r.owner)}</p><h3>${escapeText(r.title)}</h3><p>${escapeText(r.description)}</p><p class="eligibility"><strong>Who it’s for</strong>${escapeText(r.eligibility)}</p><div class="meta"><span>${escapeText(r.id==='E005'?'Confirm time with provider':r.duration==='Not published'?'See provider for details':r.duration)}</span></div><button class="detail-button" data-id="${escapeText(r.id)}">View opportunity<span class="sr-only">: ${escapeText(r.title)}</span></button></article>`).join('')||'<div class="empty"><h3>Let’s find another way forward.</h3><p>No opportunities match this combination. Remove a filter or try a broader phrase.</p><button class="button" type="button" data-empty-reset>Clear all filters</button></div>';$('#show-more').hidden=rows.length<=limit;$('#show-more').textContent='Show '+Math.min(6,Math.max(0,rows.length-limit))+' more '+(rows.length-limit===1?'opportunity':'opportunities');document.querySelectorAll('[data-stage]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.stage===s.stage)));document.querySelectorAll('[data-audience]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.audience===s.audience)));renderFilterChips('#active-filters',[{key:'audience',value:s.audience!=='Employees',label:LeadershipDiscovery.labels[s.audience]},{key:'q',value:s.q,label:'Search: '+s.q},{key:'stage',value:s.stage,label:s.stage},{key:'type',value:s.type,label:s.type}],key=>{$(mapping[key]).value=key==='audience'?'Employees':'';limit=6;render()});saveFilters(s);}
function reset(){for(const [k,id] of Object.entries(mapping))$(id).value=k==='audience'?'Employees':'';$('#hero-query').value='';limit=6;render();}
function detail(id){showOpportunity(CATALOG.find(x=>x.id===id));}
document.querySelectorAll('.opportunity-filters input,.opportunity-filters select').forEach(el=>el.addEventListener(el.tagName==='INPUT'?'input':'change',()=>{limit=6;render()}));$('#results').addEventListener('click',e=>{const b=e.target.closest('[data-id]');if(b)detail(b.dataset.id);if(e.target.closest('[data-empty-reset]'))reset()});$('#show-more').addEventListener('click',()=>{limit+=6;render()});$('#reset').addEventListener('click',reset);$('#hero-search').addEventListener('submit',e=>{e.preventDefault();$('#query').value=$('#hero-query').value;limit=6;render();$('#opportunities').scrollIntoView();$('#query').focus({preventScroll:true})});document.querySelectorAll('[data-stage]').forEach(b=>b.addEventListener('click',()=>{$('#stage').value=$('#stage').value===b.dataset.stage?'':b.dataset.stage;limit=6;render();$('#opportunities').scrollIntoView();$('#stage').focus({preventScroll:true})}));document.querySelectorAll('[data-audience]').forEach(b=>b.addEventListener('click',()=>{$('#audience').value=b.dataset.audience;limit=6;render();$('#opportunities').scrollIntoView();$('#audience').focus({preventScroll:true})}));restoreFilters(mapping);$('#hero-query').value=$('#query').value;render();
